from pathlib import Path


# Paths
BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "outputs"
FRAMES_DIR = OUTPUT_DIR / "frames"
LOGS_DIR = OUTPUT_DIR / "logs"
ROIS_DIR = OUTPUT_DIR / "rois"
VIDEOS_DIR = OUTPUT_DIR / "videos"


# Input / camera
DEFAULT_SOURCE = 0
DISPLAY_WIDTH = 1280
DISPLAY_HEIGHT = 720


# Global runtime
MAX_ANALYSIS_SECONDS = 5.0
SAVE_VIDEO = True
SAVE_FINAL_FRAME = True
SAVE_ROI_CROP = True
SHOW_FPS = True
SHOW_DEBUG_INFO = True


# Stabilization
WINDOW_SIZE = 10
STABLE_VOTE_THRESHOLD = 0.7
MIN_CONSECUTIVE_FRAMES = 3


# LED detector thresholds
GREEN_LOWER = (35, 80, 80)
GREEN_UPPER = (90, 255, 255)

RED1_LOWER = (0, 80, 80)
RED1_UPPER = (10, 255, 255)

RED2_LOWER = (170, 80, 80)
RED2_UPPER = (179, 255, 255)

LED_MIN_AREA = 80
LED_DOMINANCE_RATIO = 1.2


# Multi LED detector
MULTI_LED_SLOTS = 4
MULTI_LED_MIN_BRIGHT_PIXELS = 40
MULTI_LED_BRIGHT_THRESHOLD = 180
MULTI_LED_PASS_MIN_ON = 3
MULTI_LED_FAIL_RED_REQUIRED = True


# OCR
OCR_LANGUAGES = ["en"]
OCR_MIN_TEXT_CONFIDENCE = 0.25

OCR_PASS_WORDS = [
    "APPROVED",
    "ACCEPTED",
    "SUCCESS",
    "DONE",
    "OK",
    "PASSED",
]

OCR_FAIL_WORDS = [
    "DECLINED",
    "FAILED",
    "ERROR",
    "REJECTED",
    "TRY AGAIN",
    "FAIL",
]

# UI
FONT = 0  # cv2.FONT_HERSHEY_SIMPLEX
FONT_SCALE = 0.6
FONT_THICKNESS = 2
LINE_THICKNESS = 2
RESULT_BANNER_HEIGHT = 50